### ISSUE TITLE
"Timeout was reached" error

### ISSUE THREAD

**Issue by gilhornung** [mariodeng/FirebrowseR#13]
Hi,

I am getting a "Timeout was reached" error:

```
library(FirebrowseR)

> cohorts = Metadata.Cohorts(format = "csv") # Download all available cohorts
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
```

Thank you,

Gil

**Comment by mxxdxxx** [comment]
For me it's working. Most likely the API was unavailable.

**Comment by gilhornung** [comment]
Thank you for the reply.
Then it is probably a firewall issue on my end. Is there a way to get a
more detailed error message so I will show my IT team?
Gil

**Comment by mxxdxxx** [comment]
You could try to reach to following URL [http://firebrowse.org/api/v1/Samples](url)

You should get some JSON output. If this doesn't work, then you probably have a firewall/network problem. But please also note that this package us not under development. Due to lack of time from my side.

**Comment by gilhornung** [comment]
It is working now.
Thanks fro the help!
