### ISSUE TITLE
Creating release source

### ISSUE THREAD

**Issue by FelixMoelder** [mariodeng/FirebrowseR#14]
Hallo,

thanks for creating this package!
As additional packages like  [HTB-Record](https://github.com/jperera-bel/MTB-Report) require FirebrowseR as dependency, I would like to ask you to create a Github release of FirebrowseR.
The reason for this is, that we want to add HTB-Record to the Bioconda channel. Therefore it would be helpful to include your package with a specific release version.

**Comment by mxxdxxx** [comment]
Dear Felix,

I am delighted you're making use of that package. But did you maybe check if it's still 100% functional? I didn't do any maintenance for almost 3 year and I really can't tell if it's still working as intended.

Most probably I am not going work that anymore. But I could just hand that repos ownership over to you.

**Comment by johanneskoester** [comment]
@mariodeng, for now, a release would be all that is needed. We don't have immediate plans to continue this work, and if it fails we might consider different options. However, since it is apparently still used in the current state, the community would benefit from a release for reference regardless of whether it works or not.

**Comment by mariodeng** [comment]
If that's fine you. I just uploaded the release - please give a shot and let me know if it's working. Hope I could help you.

**Comment by mxxdxxx** [comment]
> @mariodeng, for now, a release would be all that is needed. We don't have immediate plans to continue this work, and if it fails we might consider different options. However, since it is apparently still used in the current state, the community would benefit from a release for reference regardless of whether it works or not.

If that's fine you. I just uploaded the release - please give a shot and let me know if it's working. Hope I could help you.

**Comment by FelixMoelder** [comment]
@mariodeng We've been able to create a bioconda recipe based on the release without any issues.
So FirebrowseR can easily be installed via conda, now. Thanks for helping out!

**Comment by mxxdxxx** [comment]
Glad it worked.
