### ISSUE TITLE
Improve code reusability

### ISSUE THREAD

**Issue by nuno-agostinho** [mariodeng/FirebrowseR#6]
The code in each function is highly repetitive. How about creating a general function that validates parameters, builds the query and download the data? This way, it would be easy to replace the body of the functions used in the future if needed.

**Comment by ivan-krukov** [comment]
The bulk of the user-facing functions are auto-generated from the `mustache` templates, which is why the functions are repetitive.

It would make sense to make these templates available, also.

**Comment by nuno-agostinho** [comment]
@ivan-krukov I didn't clearly explain myself. I know that the functions are auto-generated, but even then it's good practice to avoid code reuse as much as possible. So instead of repeating the same lines of code that go into each function, we can create a general function and just call it from all these specific functions.

This model also promotes [information hiding](https://en.wikipedia.org/wiki/Information_hiding) where FirebuildeR is only used to build new specific functions and it is abstracted from what the functions actually do. Therefore, if you want to change what the functions do, you'll just need to change this general function in the same project where those functions are defined (which is FirebrowseR and not FirebuildeR).

Check this example:

```r
# General function
getFirebrowseData <- function(parameters, to.Validate, invoker, method {
  validate.Parameters(params = parameters, to.Validate = to.Validate)

  url = build.Query(parameters = parameters,
                    invoker = invoker,
                    method = method)
  ret = download.Data(url, parameters$format, parameters$page)
}

# Specific function after the code has been auto-generated
Analyses.CopyNumber.Genes.Thresholded = function(format = "json",
                             cohort = "",
                             gene = "",
                             tcga_participant_barcode = "",
                             page = "1",
                             page_size = "250",
                             sort_by = "cohort"
                             ){
                             
  parameters = list(format = format,
                    cohort = cohort,
                    gene = gene,
                    tcga_participant_barcode = tcga_participant_barcode,
                    page = page,
                    page_size = page_size,
                    sort_by = sort_by)
  to.Validate = c("gene","tcga_participant_barcode")
  ret <- getFirebrowseData(parameters, to.Validate, 
                           invoker = "Analyses",
                           method = "CopyNumber/Genes/Thresholded")
  return(ret)
}
```

**Comment by ivan-krukov** [comment]
Ah, I see what you mean. That is definitely a better design. 

This also gives one central (and rather transparent) place to deal with the implementation. Also better from the version control point of view, since only one file would change (as opposed to updating all the functions).

**Comment by mariodeng** [comment]
That's a good idea, even if it's just three lines. I'll get this started asap, also feel free to contribute to FirebuildeR.
