### ISSUE TITLE
I want to add sample_type in query

### ISSUE THREAD

**Issue by arupgsh** [mariodeng/FirebrowseR#7]
Hi,

I want to use the sample_type parameter in FirebrowseR. I've tried the protocol parameter and its working fine but adding the type parameter returning "NULL" with the R package but in Firebrowse API website the query is working without any issue.

**Req url:** http://firebrowse.org/api/v1/Samples/mRNASeq?format=tsv&gene=NCOR1%2C%20CTLA4%2C%20IDO1&cohort=LAML&sample_type=NB%2CTB&protocol=RPKM&page=1&page_size=250&sort_by=cohort

**Output:**
TCGA-AB-2995	NCOR1	5.68170505957	0.0626145199137	LAML	TB	RPKM	9611
TCGA-AB-2994	NCOR1	5.64814039736	-0.0334027509284	LAML	TB	RPKM	9611
TCGA-AB-2993	NCOR1	5.70887971796	0.142005282657	LAML	TB	RPKM	9611

**With R package: **

diff.Exp.Genes = c("NCOR1", "IDO1", "CTLA4")
all.Found = F
page.Counter = 1
mRNA.Exp = list()
page.Size = 2000 # using a bigger page size is faster
while(all.Found == F){
  mRNA.Exp[[page.Counter]] = Samples.mRNASeq(format = "csv",
                                             gene = diff.Exp.Genes,
                                             cohort = "LAML",
                                             sample_type = "NB",
                                             protocol = "RPKM",
                                             page_size = page.Size,
                                             page = page.Counter)
  if(nrow(mRNA.Exp[[page.Counter]]) < page.Size)
    all.Found = T
  else
    page.Counter = page.Counter + 1
}
mRNA.Exp = do.call(rbind, mRNA.Exp)
dim(mRNA.Exp)

**Output:**

`Error in download.Data(url, format, page) : 
No samples matching your query`

**Comment by mariodeng** [comment]
Dear Arup,

please have a close look at the  `sample_type` parameters.
In your URL query you specified with two "NB" and "TB". But in your R code you just use one value, "NB". If you specify both, FirebrowseR provides the expected results:

```
> diff.Exp.Genes = c("NCOR1", "IDO1", "CTLA4")
> all.Found = F
> page.Counter = 1
> mRNA.Exp = list()
> page.Size = 2000 # using a bigger page size is faster
> while(all.Found == F){
+   mRNA.Exp[[page.Counter]] = Samples.mRNASeq(format = "csv",
+                                              gene = diff.Exp.Genes,
+                                              cohort = "LAML",
+                                              sample_type = c("NB", "TB"),
+                                              protocol = "RPKM",
+                                              page_size = page.Size,
+                                              page = page.Counter)
+   if(nrow(mRNA.Exp[[page.Counter]]) < page.Size)
+     all.Found = T
+   else
+     page.Counter = page.Counter + 1
+ }
> mRNA.Exp = do.call(rbind, mRNA.Exp)
> dim(mRNA.Exp)
[1] 537   8
```

**Comment by arupgsh** [comment]
Thanks.
